apiVersion: v1
kind: Pod
spec:
    containers:
      - name: herramientas
        image: alpine:3.23
        command:
          - cat
        tty: true
      - name: node-tool
        image: node:26
        command:
          - cat
        tty: true
      - name: kubectl-tool
        image: alpine/k8s:v1.36.1
        command:
          - cat
        tty: true