apiVersion: v1
kind: ResourceQuota
metadata:
  name: curso-contendores-quota
  namespace: curso-contenedores
spec:
  hard:
    requests.cpu: "6000m"
    requests.memory: "16Gi"
    limits.cpu: "10000m"
    limits.memory: "32Gi"

    count/pods: "30"
    count/services: "3"
    count/configmaps: "10" 
    count/secrets: "2" 
    count/ingresses.networking.k8s.io: "3"
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: curso-contenedores-hpa
  namespace: curso-contenedores
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: curso-contenedores
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15



